### ISSUE TITLE
The colab notebook is only for Kivy python apps?

### ISSUE THREAD

**Issue by Rafail-P** [kaustubhgupta/KivyMLApp#2]
I apologize for the inconvenience.
 I read the article about converting a python application to apk and I tried to use the colab notebook you posted, but it didn't work. Does the colab notebook only work for python applications made with Kivy? The python application I want to convert uses the PySide2 module. The colab notebook must be rewrite to compile this python application?
Thanks for any hints.
This is the colab log:
[Colab log.txt](https://github.com/kaustubhgupta/KivyMLApp/files/6137333/Colab.log.txt)

**Comment by kaustubhgupta** [comment]
Yes, that Colab notebook only works for Python apps made in Kivy framework

**Comment by Rafail-P** [comment]
Thanks for the reply.
For applications written in PySide2 (this module is the python part of the Qt5 Compiler) what differences should be applied to the colab notebook? (If I don't bother you too much and if it is not to hard to do...)

**Comment by kaustubhgupta** [comment]
Actually Kivy framework has whole new structure and it will take time to map the exact same functions into Kivy. You can refer to my articles and docs for building the app and after that only, you can convert that app into equivalent Android app.

**Comment by Rafail-P** [comment]
Thanks for reply. I'll try to read the documentation...
