### ISSUE TITLE
How did you generate APK?

### ISSUE THREAD

**Issue by susumuasaga** [kaustubhgupta/KivyMLApp#4]
I tested the APK files in this repo on my phone and they worked.
But when I issue the command `buildozer -v android debug`, I get the APK generated in the /bin directory, but when I  test it on my phone, the app just crashes after a couple of seconds. I am using Ubuntu WSL-2 on Windows 10. 
When I don't use KivyMD, just plain Kivy, the app works well and does not crash.
I want to know what I am doing wrong.
Thank you.

**Comment by kaustubhgupta** [comment]
Check out this article and let me know if you're doing the same things as instructed.

https://towardsdatascience.com/3-ways-to-convert-python-app-into-apk-77f4c9cd55af

**Comment by kaustubhgupta** [comment]
I am assuming that your issue was resolved. Feel free to ask again :)

**Comment by susumuasaga** [comment]
I just gave up using KivyMD. I plain Kivy builds without issue.
