### ISSUE TITLE
Is there possible I do a simple OpenCV with just play the video, and I use this to convert to apk?

### ISSUE THREAD

**Issue by SamYokai** [kaustubhgupta/KivyMLApp#5]
Now I'm want to do something with OpenCV and it just very simple which only play a video, and I would like to generate into apk with using your method. I only can do it on Google Colab, so just want to confirm with you that did this method can help me to generate my OpenCV video into apk?

**Comment by SamYokai** [comment]
by the way, also want to confirm, if there generate a apk file, is it just open the apk file only? for the main.py and the spec file, is these need together with the apk such as same location with the apk file?

**Comment by kaustubhgupta** [comment]
- For APK, you don't need any other file. The APK file is enough to run the application on Android devices
- For OpenCV, you need to try converting the application as I don't know if buildozer conversion supports OpenCV.
